[package]
name = "tls13"
version = "0.1.0"
edition = "2021"
rust-version = "1.78.0"

[dependencies]
aes = "0.8.4"
aes-gcm = "0.10.3"
hex-literal = "0.4.1"
hkdf = "0.12.4"
num-derive = "0.4.2"
num-traits = "0.2.19"
p256 = { version = "0.13.2", features = ["ecdh"] }
rand = "0.8.5"
sha2 = "0.10.8"
